services:
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - "5000:80"
      - "2525:25"
    networks: [appnet]

  app:
    build: .
    environment:
      EMAIL_SERVER_HOST: smtp4dev
      EMAIL_SERVER_PORT: 25
      SMTP_SECURE: "false"
    depends_on: [smtp4dev]
    networks: [appnet]

networks:
  appnet:
    driver: bridge
